version: "1"
services:
  # Add your containers here, specifying the base image you want to build from
  # For example:
  #
  infrared:
     image: stefanlehmann/centos-jenkins-docker-slave

registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx   